@baseUrl = http://localhost:5000
### Authorization code + PKCE
# Password grant was removed. Use Swagger Authorize (OAuth2, PKCE, client_id=spa)
# or a public client against:
#   GET  {{baseUrl}}/connect/authorize
#   POST {{baseUrl}}/connect/token
# Login page: {{baseUrl}}/account/login
