IF DB_ID(N'MyMeetings') IS NULL
BEGIN
    CREATE DATABASE [MyMeetings]
END
GO

USE [MyMeetings]
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'app')
BEGIN
    EXEC(N'CREATE SCHEMA app AUTHORIZATION dbo')
END
GO